// <auto-generated />
using HandInHandOut.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HandInHandOut.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211003013144_Addphotopath")]
    partial class Addphotopath
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HandInHandOut.Models.Books", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BuyingAmount")
                        .HasColumnType("float");

                    b.Property<int>("IsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("Major")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBooksAvailable")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RentingAmount")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Author = "Syed Abdul Suboor",
                            BuyingAmount = 12.99,
                            IsAvailable = 0,
                            Major = 1,
                            Name = "C# For Dummies",
                            NumberOfBooksAvailable = 20,
                            RentingAmount = 0.20000000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
